services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Etc/UTC'
      PIHOLE_DNS_: 'dns-primary#5301;dns-secondary#5301'
      WEBPASSWORD: 'Secure1-Password-Here'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './dnsmasq/02-allservers.conf:/etc/dnsmasq.d/02-allservers.conf'
      - './dnsmasq/03-forward.conf:/etc/dnsmasq.d/03-forward.conf'
    restart: unless-stopped

  dns-primary:
    container_name: dns-primary
    image: coredns/coredns:latest
    command: ["-conf", "/etc/coredns/Corefile"]
    expose:
      - 5301/udp
    volumes:
      - './coredns/Corefile:/etc/coredns/Corefile'
    restart: unless-stopped

  dns-secondary:
    container_name: dns-secondary
    image: coredns/coredns:latest
    command: ["-conf", "/etc/coredns/Corefile"]
    expose:
      - 5301/udp
    volumes:
      - './coredns/Corefile:/etc/coredns/Corefile'
    restart: unless-stopped